### ISSUE TITLE
missing `./src/converter`

### ISSUE THREAD

**Issue by ScottChapman** [yanickrochon/universal-converter#1]
So when I include this package in my project (`npm install --save universal-converter`) and then require it in my code:
```
const Converter = require('universal-converter')
```
I get and error saying `./src/converter` is not found, and sure enough it doesn't exist in my `node_modules` folder...

**Comment by yanickrochon** [comment]
Oh, that is a problem! I initially wrote this for a project, and used it successfully, so I'm shocked at this issue. I will fix that ASAP

**Comment by yanickrochon** [comment]
Fixed with 4e99b19991a7cc050c290a058bb06c0561ce93ac

**Comment by ScottChapman** [comment]
```
$ npm install universal-converter
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN converter@1.0.0 No description
npm WARN converter@1.0.0 No repository field.

+ universal-converter@1.6.1
added 1 package from 1 contributor and audited 1 package in 0.431s
found 0 vulnerabilities

$ node
> const converter = require('universal-converter')
node_modules/universal-converter/index.js:6
import Converter from './converter';
       ^^^^^^^^^

SyntaxError: Unexpected identifier

```

**Comment by yanickrochon** [comment]
I was afraid this might happen :) I'm using Babel is all my projects now. I'll see what I can do about that, because the build process I now use creates transpiled modules.

**Comment by ScottChapman** [comment]
Yea, that's kinda what I figured. Not a big Babel fan for non-UI projects...

**Comment by yanickrochon** [comment]
Alright, I have made a quick test, and I think 1.6.2 is good.

**Comment by ScottChapman** [comment]
works!
